### ISSUE TITLE
Considering KenLM for n-gram language modeling

### ISSUE THREAD

**Issue by alexcannan** [florisboard/nlp#8]
Hi there,

I am a new user of florisboard as of this morning, and I couldn't help but get caught up with the development news. I have taken a quick look at your nlp package and noticed (possibly incorrectly) that it uses a home-cooked n-gram language modeling for suggestions. I wanted to formally suggest utilizing the [KenLM library](https://github.com/kpu/kenlm) for this. It is very lightweight and fast. I've used it extensively for speech recognition applications during the decoder step, and I would think speech decoding shares similar goals with keyboard word suggestions (speed, small memory footprint). 

I will say I've never considered integrating it directly with another C++ application like this, I've only used its standalone executables, but I would imagine it's possible to weave them together. But, my C++ is rusty. Anyways, if this is interesting to the developers I could do some groundwork for you, let me know.

**Comment by patrickgold** [comment]
Hey,

sorry for the late answer. I've had a look at the KenLM library and generally it looks really intriguing, however sadly it is licensed LGPL/GPL which is not compatible with this project's Apache 2.0 license.

Will close this issue thus.
